parameters:
    env(EMSCH_ELASTICSEARCH_CLUSTER): '["http://localhost:9200"]'
    env(EMSCH_LIVE_INDEX): preview
    env(EMSCH_PREVIEW_INDEX): preview
    env(EMSCH_PREVIEW_REGEX): /preview/
    env(EMSCH_INSTANCE_ID): website_
    env(EMSCH_TRANSLATION_TYPE): label
    env(EMSCH_TEMPLATE_TYPE): template

ems_backend_bridge:
    request_environments:
        preview:
           regex: '%env(string:EMSCH_PREVIEW_REGEX)%'
           index: '%env(string:EMSCH_PREVIEW_INDEX)%'
        live:
           regex: '/.*/'
           index: '%env(string:EMSCH_LIVE_INDEX)%'
    elasticms:
        website:
            #cluster: '%env(json:EMSCH_ELASTICSEARCH_CLUSTER)%'
            hosts: '%env(json:EMSCH_ELASTICSEARCH_CLUSTER)%'
            index_prefix: '%env(string:EMSCH_INSTANCE_ID)%'
            translation_type: '%env(string:EMSCH_TRANSLATION_TYPE)%'
            template_type: '%env(string:EMSCH_TEMPLATE_TYPE)%'
    clear_cache: website