parameters:
    env(EMSCH_INSTANCE_ID): website_
    env(EMSCH_ELASTICSEARCH_CLUSTER): '["http://localhost:9200"]'
    env(EMSCH_LOCALES): '["fr","nl"]'

    env(EMSCH_LIVE_INDEX): live
    env(EMSCH_PREVIEW_INDEX): preview
    env(EMSCH_PREVIEW_REGEX): '/preview/'

    env(EMSCH_TRANSLATION_TYPE): label
    env(EMSCH_TEMPLATES): '{}'
    env(EMSCH_ROUTES): '{}'

ems_client_helper:
    locales: '%env(json:EMSCH_LOCALES)%'
    request_environments:
        preview:
           regex: '%env(string:EMSCH_PREVIEW_REGEX)%'
           index: '%env(string:EMSCH_PREVIEW_INDEX)%'
           backend: '%env(string:EMSCH_BACKEND_URL)%'
        live:
           regex: '/.*/'
           index: '%env(string:EMSCH_LIVE_INDEX)%'
    elasticms:
        website:
            hosts: '%env(json:EMSCH_ELASTICSEARCH_CLUSTER)%'
            index_prefix: '%env(string:EMSCH_INSTANCE_ID)%'
            translation_type: '%env(string:EMSCH_TRANSLATION_TYPE)%'
            templates: '%env(json:EMSCH_TEMPLATES)%'
            routes: '%env(json:EMSCH_ROUTES)%'

    template_language: '%env(string:EMSCH_TEMPLATE_LANGUAGE)%'
    routing:
        client_request: website
        redirect_type: '%env(string:EMSCH_REDIRECT_TYPE)%'