services:
    EMS\CommonBundle\Storage\Adapter\HttpAdapter:
        tags: [ems_common.storage.adapter]
        arguments:
            - '%env(STORAGE_PATH)%'
            - '%env(string:EMSCH_BACKEND_URL)%'
